### ISSUE TITLE
What is the difference btw DGM and PINNs

### ISSUE THREAD

**Issue by ShihaoCui** [pooyasf/DGM#1]
Hello there,

 thanks for your sharing. It's a great job.

I am also testing some PINNs codes. In my humble opinion, the method right here you are sharing here, i.e. DGM is very similar or almost identical to the most common method, PINNs(Physics informed neural networks).

So what's the difference btw DGM and PINNs?

Regards
Shihao

**Comment by pooyasf** [comment]
Hi Shihao,

PINN is a general term that refers to both forward and inverse methods discussed in the paper by M.Raissi et al. paper. The DGM is just a forward method (for finding the solution given the equation) which is pretty similar to PINN forward procedure.

So, mathematically they are doing similar things but in the DGM paper, they have introduced some other tips and tricks like sampling free boundaries which is novel compared to PINN paper.

Anyway, I believe the difference is mostly the matter of terminology, not core mathematical formulation.

Best,
Pooya

**Comment by ShihaoCui** [comment]
Hi Pooya,

Thanks for your great sharing. Best wishes to your and also my projects. :)

Regards
Shihao
